add nm_join_bayes
metrumresearchgroup/bbr.bayes pull request #106
Opened 2023-11-07 00:18 UTC by kyleam

When working on `run_sims` in gh-75, we decided to focus on the return value and rename the function to `nm_join_bayes`, treating it as the nmbayes analog of `nm_join`.  Going that direction led to gh-96, and consensus from discussion there was that 1) we should try to align with `nm_join` as closely as possible (e.g., support `.files`) and 2) ideally `nm_join` would be used underneath to avoid repeating some its more complicated logic.

This series implements that proposal and supersedes gh-75.  Most notable changes from gh-75:

 * Use `nm_join` underneath.

 * Don't write behind-the-scenes table when submitting model; instead use the `nm_join` default for the tables and allow callers to specify file via `.files`.

 * Drop argument for specifying custom data; instead add an argument that allows callers to specify a function that can be used to transform the data after the table-to-data join but before simulating with mrgsolve.

 * Support `.superset = TRUE`.

 * Drop `log_dv` argument; see discussion in gh-97.  (I'll follow up there.)

 * Flesh out tests.  At some point, @seth127 and I think it'd be nice to have the SME-inspected tests along the lines of what's discussed in gh-75, but we're not sure what that will look like, and it's likely to live outside this test suite, so we're not considering it a blocker for merging this PR.

Closes #46.
Closes #50.
Closes #96.
Closes #100.

Re: #97

cc: @kylebaron @timwaterhouse

---

- [ ] Open PR `nm_join` "origin attribute" PR for bbr.  (This PR introduces handling for that feature but also has fallback code for older bbr versions.)

2023-11-07 00:26 UTC, kyleam commented on R/nm-join-bayes.R
> +#'   required for the mrgsolve simulation (e.g., renaming a column to "TIME").
I don't love the name `presim_fn`.   If anyone has better ideas, let me know.

2023-11-07 00:28 UTC, kyleam commented on R/nm-join-bayes.R
> +  origin <- attr(dfs[[1]], "nm_join_origin")
This is the bit that will require a PR on bbr's side.

2023-11-13 21:53 UTC, seth127 requested changes
This is all looking great to me. I left some comments, but they're all documentation things. 

The core code here has been reviewed by myself and various scientific SMEs several times now, so I think we're good to merge this now (pending docs edits). After that, we'll run it through the paces on some more realistic models and see if we come up with anything we want to change before the initial release.

Great work here.

2023-11-13 21:53 UTC, seth127 commented on R/nm-join-bayes.R
> +  if (!inherits(x, "data.frame")) {
These checks all look good to me. We're kind of getting into deep water here with letting the user pass in a function, but if the results passes these checks... I guess I think we're doing our due diligence.

2023-11-14 17:26 UTC, kyleam commented on R/nm-join-bayes.R
> +    stop("`.files` must be relative paths.")
Good catch.  Added in 1778067.

2023-11-14 17:26 UTC, kyleam commented on R/nm-join-bayes.R
> +      stop("`npde = TRUE` requires npde package.")
Doh, fixed in a36551d.

2023-11-14 17:26 UTC, kyleam commented on R/nm-join-bayes.R
> +#' @param .files Paths to table files to pass to [bbr::nm_join()] calls (on per
fixed in 3cbf3c5

2023-11-14 17:29 UTC, kyleam commented
@seth127 Thanks for the review.   Pushed updates.   Back to you.

2023-11-14 19:41 UTC, seth127 approved these changes
Looking great. Thanks again for all the work on this.

2023-11-14 20:07 UTC, merged